version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: sat-postgres
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sat-result
    networks:
      - default
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres: